### ISSUE TITLE
time typeerror bug

### ISSUE THREAD

**Issue by will-fawcett** [st-bender/pynrlmsise00#1]
Hello, 

I was recently using your package, installed via pip. I get a type error from this line: 
https://github.com/st-bender/pynrlmsise00/blob/master/src/nrlmsise00/core.py#L157

In particular, elsewhere in the code there is a conversion to `numpy.datetime64` , which does not have a "year" attribute. 

In my case I was able to fix the problem by casting the `time` variable as follows:
```
time = pd.to_datetime(time)
```

**Comment by st-bender** [comment]
Hi @will-fawcett 

Thanks for reporting.

> elsewhere in the code

You mean in your code, or in this module's code?
Could you provide an example of what you are trying to do?

The function expects a `datetime.dateime`, or anything that provides the required attributes, such as pandas dateimes.
If this happens in the module this is a bug.
Otherwise, I intentionally left the conversion to the caller, maybe this could be documented better.

Cheers.

**Comment by will-fawcett** [comment]
Hi @st-bender ,

Thank you for the response. Apologies for the confusion in my initial email.

I call the `msise_flat` function (from your module), and the first argument that I pass to that function is a date, this date is of type `pandas.DatetimeIndex`. Somewhere inside your module, this is converted to a `numpy.datetime64` type, and hence the bugfix needing a cast.

**Comment by st-bender** [comment]
Hi @will-fawcett 

It would be helpful to have a little example code and the numpy and pandas version. I don't know if you are familiar with the Github interface, you can paste code with triple backticks ``` like this:

```
```py
import numpy
import pandas

print(numpy.__version__)
print(pandas.__version__)

<your code here...>
(close with triple backticks ```)
```

It will then look like this:

```py
import numpy
import pandas

print(numpy.__version__)
print(pandas.__version__)

<your code here...>

```

And the output in the same way.

You don't have to paste everything, just a little example that exhibits the error. It is not only helpful for me, but maybe for others too that may stumble upon that issue.

From your description, it sounds like you need to convert the pandas index to `datetime.datetime`s, you can use `<DatetimeIndex>.to_pydatetime()` for that:

```py
msise_flat(index.to_pydatetime(), alt, lat, lon, ...)
```

Another question is, what are you actually trying to do?
There is also a `dataset` extra that can output to `xarray.Dataset` if you need multiple outputs nicely packaged, details are in the readme.

Cheers.

**Comment by st-bender** [comment]
Hi @will-fawcett 

Does using `index.to_pydatetime()` work?
I added more description to the function docs to help people using pandas, is that clearer now?

I'd like to keep the base requirements minimal as pandas itself brings a lot of other dependencies with it. The other thing is that `pd.to_datetime()` might not work for other inputs such as `astropy.time.Time` objects, and it would be called for every single element.
Thus I think it is better to convert everything beforehand. I'll also update the readme, but let me know if you think of other places where to put this hint so people can find it more easily the next time.

Cheers.
